services:
  - type: web
    name: creditcard-mt940
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    env:
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
    healthCheckPath: /_stcore/health